### ISSUE TITLE
R7 240 

### ISSUE THREAD

**Issue by wxjer** [linkua/OC_AMD870k_R7_240#1]
哥们，请教下，同款显卡，你是给显卡刷了vbios么然后仿冒的ID么？有木有刷这个卡刷bios教程，

**Comment by linkua** [comment]
是的， 我是用AMD and Nvidia GOP update 1.9.3 给刷的支持UEFI，搜“显卡刷uefi”就有好多教程，例如https://baijiahao.baidu.com/s?id=1663271979535219945&wfr=spider&for=pc，刷完是UEFI那里就打勾了
![R7240](https://user-images.githubusercontent.com/24735753/123590266-01c0dd00-d81d-11eb-9e64-e077b0a28a99.gif)

**Comment by wxjer** [comment]
THX

**Comment by wxjer** [comment]
哥们 再次打扰一下，我这张卡插上就能用，11.4的系统，系统报告里显卡id为6613（R7 240），显存只有6MB，
我这边按照[教程](https://dortania.github.io/Getting-Started-With-ACPI/Universal/spoof.html)仿冒的id为何一直不生效，model信息也未发生改变，你有做过什么别的操作么？类似于修复权限，重建缓存之类

**Comment by linkua** [comment]
我显卡原来id也是6613，我仿冒的是6798，没有做其他操作，就在OC里加一个SSDT-GPU-SPOOF.aml文件，就可以了。你可以参考对比下
[SSDT-GPU-SPOOF.txt](https://github.com/linkua/OC_AMD870k_R7_240/files/6732441/SSDT-GPU-SPOOF.txt)
![屏幕截图](https://user-images.githubusercontent.com/24735753/123778066-5474c480-d903-11eb-990d-21a26ae2a452.png)
![屏幕截图1](https://user-images.githubusercontent.com/24735753/123778085-576fb500-d903-11eb-82ea-e5b7d78dc1a1.png)
![屏幕快照2 (2)](https://user-images.githubusercontent.com/24735753/123778097-59d20f00-d903-11eb-8b2b-94e5d4518fae.png)

**Comment by wxjer** [comment]
刚用了你说的1.9.3重新生成了一个bios rom，发现竟然跟之前用最新版生成的rom大小不一样，于是刷了这个1.9.3的rom，但是不管老旧rom在设备管理器->R7 240 属性->详情 里都没有【 Bios 设备名字】 这一项。
所以我的ACPI路径用的是【 位置路径 】里面的: SB.PCI0.GPP8，见图一，但是进了OS之后，HackinTool 看到的路径却是：PCI0@0/GPP8@3,1/GFX0@0 ，这就有点搞不懂了。
[](url)
显卡驱动是2021.5.21那版

显卡属性-》事件 里面显示有需要完成安装的提示 不清楚你的有没有，可能是刷bios导致的问题。

所以用这两个路径分别测试了注入spoof.aml ，都不行。
现在怀疑的是一直没注入成功，甚至没走到注入，因为model字段从未更新过，但是通过在config.plist.DeviceProperties 加入device-id =13660000 和 model = R7 240 字段， 却能更新model字段，device-id却不行

还有就是我的系统是11.4，但是教程里写的240是能支持到Big Sur的。

目前猜测是whatevergreen注入了一个6613ID，并覆盖了我的注入，patch了一个新的acpi path，这也可能是我在HackinTool里找到的路径与win下不同的原因。

**Comment by wxjer** [comment]
![83A7B4A5-A832-4E28-8DAD-4FACFC1777DA](https://user-images.githubusercontent.com/13941095/123800516-f4d6e300-d91b-11eb-9bd5-68bf3110f6fa.png)
![3AB87052-2228-4738-A9B4-4D3D1CB92D4B](https://user-images.githubusercontent.com/13941095/123800532-fb655a80-d91b-11eb-852b-a0baf00fa310.png)
![iShot2021-06-29 20 39 55](https://user-images.githubusercontent.com/13941095/123800560-028c6880-d91c-11eb-82d5-5919c3d5dcf5.png)
![iShot2021-06-29 20 49 26](https://user-images.githubusercontent.com/13941095/123800593-0a4c0d00-d91c-11eb-8e82-1b52e7e28011.png)

**Comment by linkua** [comment]
能支持UEFI启动就不用刷rom了，你的不用刷rom了，因为都能显示了，仿冒ID没成功而已。windows显卡驱动没有问题，可能不同厂商的有点差异吧，显卡属性没有Bios 设备名字也没关系，ACPI路径以windows的位置路径为准，不管HackinTool 的，你现在没有注入成功，spoof.aml 没有起作用，不需要修改config.plist.DeviceProperties，也和whatevergreen没关系，默认就行。注入成功后，设备ID会变成你仿冒的ID。你按教程在spoof改你自己的ACPI路径 _SB_.PCI0.GPP8, device ID：用0x98,0x67,0x00,0x00, model:这个内容只是说明，不起作用。影响SSDT注入的就ACPI路径和device ID，Big Sur系统我没试过，教程说支持应该就是支持的。

**Comment by Yidadaa** [comment]
写给其他想要使用 R7 240 装黑苹果的人：这张卡最高只支持到 MacOS 10.x 系统。

也就是说 Big Sur 及其以上的系统，只能达到半驱动状态，即系统可以识别显卡型号和显存，但是没有 Metal 支持，这意味着所有系统级的高斯模糊效果都是缺失的，可以看下面的截图， Dock 栏本应该是高斯模糊，现在只能显示为全黑。其次所有的系统动画都会非常卡顿，比如窗口从 Dock 栏飞出的动效。此外窗口拖动时会有撕裂感觉。

其他所有 Oland 核心的显卡，比如 R7 240/340 等，详见[这个页面](https://www.techpowerup.com/gpu-specs/amd-oland.g389)中列出的显卡。

这一点在国外的黑苹果论坛可以得到验证，至今没人能在 Big Sur 及以上系统成功完全驱动过这张卡。

![image](https://user-images.githubusercontent.com/16968934/198604035-ca69c9d5-6f7d-43ba-877a-d94223a9704e.png)
